line-length = 320 # I don't like text wrapping
indent-width = 4
preview = true

[format]
line-ending = "lf"

[lint]
select = ["ALL"]
ignore = [
    "missing-copyright-notice", # Ignore license header checks
    "undocumented-public-module",   # Ignore missing doc strings in modules
    "incorrect-blank-line-before-class",   # Conflicts with D211 (we like no blank line before class docstring)
    "multi-line-summary-second-line",   # Conflicts with D212 (we like first docstring line at top)
]
